// maps an entity name to the png filename picturing the entity 
export const entity_name_to_png: Record<string, string> = {
"adobe" : "adobe.png",
"AI" : "AI.png",
"amazon" : "amazon.png",
"kuiper" : "amazon.png",
"project kuiper" : "amazon.png",
"americans" : "america.png",
"america" : "america.png",
"US" : "america.png",
"USA" : "america.png",
"united states" : "america.png",
"android" : "android.png",
"skyrim" : "skyrim.png",
"baldur" : "baldur.png",
"baldurs" : "baldur.png",
"baldur's gate" : "baldur.png",
"zelda" : "zelda.png",
"breath of the wild": "zelda.png",
"legend of zelda" : "zelda.png",
"final fantasy" : "final_fantasy.png",
"final fantasy xii" : "final_fantasy.png",
"final fantasy x" : "final_fantasy.png",
"halo": "halo.png",
"ODST": "halo.png",
"ezio": "ezio.png",
"mass effect": "mass_effect.png",
"black flag": "black_flag.png",
"factorio": "factorio.png",
"playstation": "playstation.png",
"PS": "playstation.png",
"wii": "wii.png",
"helldivers": "helldivers.png",
"balatro": "balatro.png",
"ubisoft": "ubisoft.png",
"robert pattinson": "robert_pattinson.png",
"fallout": "fallout.png",
"new vegas": "fallout.png",
"indiana jones": "indiana_jones.png",
"atomfall": "atomfall.png",
"south of midnight": "south_of_midnight.png",
"avowed": "avowed.png",
"blue prince": "blue_prince.png",
"gundam": "gundam.png",
"stellar blade": "stellar_blade.png",
"obra dinn": "obra_dinn.png",
"astrobot": "astrobot.png",
"delta force": "delta_force.png",
"clair obscur": "clair_obscur.png",
"clair obscura": "clair_obscur.png",
"diablo": "diablo.png",
"CDPR": "CDPR.png",
"guilty gear": "guilty_gear.png",
"split fiction": "split_fiction.png",
"morrowind": "morrowind.png",
"game pass": "gamepass.png",
"gamepass": "gamepass.png",
"elder scrolls": "elder_scrolls.png",
"bloodborne": "bloodborne.png",
"blood borne": "bloodborne.png",
"dying light": "dying_light.png",
"sony": "sony.png",
"bioshock": "bioshock.png",
"capcom": "capcom.png",
"dark arisen": "dark_arisen.png",
"subnautica": "subnautica.png",
"crisis core" : "final_fantasy.png",
"rocket league" : "rocket_league.png",
"elden ring" : "elden_ring.png",
"elden" : "elden_ring.png",
"stardew" : "stardew.png",
"stardew valley" : "stardew.png",
"dark souls": "dark_souls.png",
"cyberpunk": "cyberpunk.png",
"starfield": "starfield.png",
"honda": "honda.png",
"takis": "takis.png",
"armenia": "armenia.png",
"armenian": "armenia.png",
"ncaa": "NCAA.png",
"NCAAs": "NCAA.png",
"depop": "depop.png",
"bay area": "silicon_valley.png",
"hamas": "hamas.png",
"army": "army.png",
"us army": "army.png",
"u.s. army": "army.png",
"iron man": "iron_man.png",
"avengers": "avengers.png",
"GTA": "GTA.png",
"chicago": "chicago.png",
"south africa": "south_africa.png",
"south african": "south_africa.png",
"BMW": "BMW.png",
"red bull": "red_bull.png",
"monster": "monster.png",
"eleanor roosevelt": "eleanor_roosevelt.png",
"lebron": "lebron_james.png",
"lebron james": "lebron_james.png",
"marine corps": "marine_corps.png",
"philosophy": "philosophy.png",
"turkey": "turkey.png",
"nissan": "nissan.png",
"apple" : "Apple.png",
"iphone" : "Apple.png",
"iphones" : "Apple.png",
"pentagon": "pentagon.png",
"powell": "powell.png",
"australia" : "australia.png",
"berkeley" : "berkeley.png",
"bezos" : "bezos.png",
"jeff bezos" : "bezos.png",
"biden" : "biden.png",
"bumble" : "bumble.png",
"canada" : "canada.png",
"canadians" : "canada.png",
"reagan": "ronald_reagan.png",
"ronald reagan": "ronald_reagan.png",
"gameboy": "gameboy.png",
"gameboy advance": "gameboy.png",
"lucky charms": "lucky_charms.png",
"hulu": "hulu.png",
"burger king": "burger_king.png",
"ipad": "Apple.png",
"airpods": "Apple.png",
"airpod": "Apple.png",
"mexico": "mexico.png",
"mexican": "mexico.png",
"happy endings": "happy_endings.png",
"lindsay lohan": "lindsay_lohan.png",
"lohan": "lindsay_lohan.png",
"gisele": "gisele_bundchen.png",
"gisele bundchen": "gisele_bundchen.png",
"ivanka trump": "ivanka_trump.png",
"ivanka": "ivanka_trump.png",
"tom brady": "tom_brady.png",
"brady": "tom_brady.png",
"hollywood": "hollywood.png",
"scientology": "scientology.png",
"harry potter": "harry_potter.png",
"jk rowling": "jk_rowling.png",
"rowling": "jk_rowling.png",
"rome": "rome.png",
"roman": "rome.png",
"ariana grande": "ariana_grande.png",
"ariana": "ariana_grande.png",
"israel": "israel.png",
"jews": "israel.png",
"jewish": "israel.png",
"jew": "israel.png",
"zionist": "israel.png",
"zionism": "israel.png",
"greece": "greece.png",
"greek": "greece.png",
"hugh grant": "hugh_grant.png",
"pedro pascal": "pedro_pascal.png",
"the last of us": "the_last_of_us.png",
"bella ramsey": "bella_ramsey.png",
"george clooney": "george_clooney.png",
"clooney": "clooney.png",
"eagles": "philadelphia_eagles.png",
"philadelphia eagles": "philadelphia_eagles.png",
"philly eagles": "philadelphia_eagles.png",
"covid": "covid.png",
"covid-19": "covid.png",
"covid 19": "covid.png",
"coronavirus": "covid.png",
"corona virus": "covid.png",
"chatgpt" : "chatgpt.png",
"chat gpt" : "chatgpt.png",
"gpt" : "chatgpt.png",
"FBI": "FBI.png",
"david burns": "david_burns.png",
"china" : "china.png",
"chinese" : "china.png",
"ukraine": "ukraine.png",
"ukrainian": "ukraine.png",
"congress": "congress.png",
"christianity" : "Christianity.png",
"christian" : "Christianity.png",
"bible" : "Christianity.png",
"jesus" : "Christianity.png",
"jesus god" : "Christianity.png",
"christ" : "Christianity.png",
"jesus christ": "Christianity.png",
"europe": "europe.png",
"european": "europe.png",
"north korea": "north_korea.png",
"chrome" : "chrome.png",
"chromium" : "chrome.png",
"xfinity": "xfinity.png",
"california": "california.png",
"californian": "california.png",
"Cal": "california.png",
"CA": "california.png",
"UCB": "UCB.png",
"ayn rand": "ayn_rand.png",
"atlas shrugged": "ayn_rand.png",
"the fountainhead": "ayn_rand.png",
"kubrick": "kubrick.png",
"RFK": "RFK.png",
"RFK Jr.": "RFK.png",
"RFK Jr": "RFK.png",
"Robert F. Kennedy": "RFK.png",
"YC": "ycombinator.png",
"y combinator": "ycombinator.png",
"ycombinator": "ycombinator.png",
"startx": "startx.png",
"Robert F. Kennedy Jr.": "RFK.png",
"ASU": "arizona_state_university.png",
"arizona state university": "arizona_state_university.png",
"faang": "faang.png",
"STEM": "STEM.png",
"communism": "communism.png",
"communist": "communism.png",
"stanley kubrick": "kubrick.png",
"bitcoin": "bitcoin.png",
"BTC": "bitcoin.png",
"nato": "nato.png",
"soviet union": "soviet_union.png",
"soviet": "soviet_union.png",
"USSR": "soviet_union.png",
"soviets": "soviets.png",
"university of zurich": "university_of_zurich.png",
"columbia" : "columbia.png",
"columbia university" : "columbia.png",
"columbiau" : "columbia.png",
"deepseek" : "deepseek.png",
"coinbase": "coinbase.png",
"ethereum": "ethereum.png",
"fed": "Fed.png",
"federal reserve": "Fed.png",
"federal reserve system": "Fed.png",
"fidelity": "fidelity.png",
"wawa": "wawa.png",
"FNCMX": "fidelity.png",
"fidelity investments": "fidelity.png",
"nasdaq": "nasdaq.png",
"iraq": "iraq.png",
"irs": "irs.png",
"earth": "earth.png",
"UN": "UN.png",
"united nations": "UN.png",
"robinhood": "robinhood.png",
"democrats" : "democrats.png",
"DNC": "democrats.png",
"democratic": "democrats.png",
"whatsapp": "whatsapp.png",
"Constitution": "america.png",
"bytedance": "bytedance.png",
"excel": "excel.png",
"denmark": "denmark.png",
"satya nadella": "satya_nadella.png",
"satya": "satya_nadella.png",
"nadella": "satya_nadella.png",
"alexander zverev": "alexander_zverev.png",
"alex zverev": "alexander_zverev.png",
"geoffrey hinton": "geoffrey_hinton.png",
"hinton": "geoffrey_hinton.png",
"claude": "claude_ai.png",
"claude ai": "claude_ai.png",
"claudeai": "claude_ai.png",
"zverev": "alexander_zverev.png",
"Dems" : "democrats.png",
"democrat" : "democrats.png",
"abraham lincoln": "lincoln.png",
"lincoln": "lincoln.png",
"palestine": "palestine.png",
"palestinian": "palestine.png",
"palestinians": "palestine.png",
"liberal" : "democrats.png",
"liberals" : "democrats.png",
"DHL" : "DHL.png",
"discord" : "discord.png",
"DoD" : "DoD.png",
"duolingo" : "duolingo.png",
"duo": "duolingo.png",
"FCC": "FCC.png",
"elon" : "elon.png",
"elon musk" : "elon.png",
"musk" : "elon.png",
"EU" : "EU.png",
"el salvador": "salvador.png",
"salvador": "salvador.png",
"facebook" : "facebook.png",
"FB" : "facebook.png",
"neuralink": "neuralink.png",
"Figure": "Figure.png",
"cordycepin": "cordycepin.png",
"ray kurzweil": "ray_kurzweil.png",
"kurzweil": "ray_kurzweil.png",
"thomas kurian": "thomas_kurian.png",
"kurian": "thomas_kurian.png",
"chargepoint": "chargepoint.png",
"QBL": "physics.png",
"general atomics": "general_atomics.png",
"unitree": "unitree.png",
"moon": "moon.png",
"AGI": "AI.png",
"isaac newton": "isaac_newton.png",
"newton": "isaac_newton.png",
"firefox" : "firefox.png",
"Ford" : "Ford.png",
"france" : "france.png",
"french": "france.png",
"asia": "asia.png",
"asian": "asia.png",
"indonesia": "indonesia.png",
"indonesian": "indonesia.png",
"CS": "computer_science.png",
"computer science": "computer_science.png",
"coding": "computer_science.png",
"lego": "lego.png",
"legos": "lego.png",
"netflix": "netflix.png",
"germany" : "germany.png",
"german" : "germany.png",
"google" : "google.png",
"google search" : "google.png",
"the office": "the_office.png",
"breaking bad": "breaking_bad.png",
"seinfeld": "seinfeld.png",
"carney": "mark_carney.png",
"mark carney": "markey_carney.png",
"diana": "princess_diana.png",
"princess diana": "princess_diana.png",
"robin williams": "robin_williams.png",
"david bowie": "david_bowie.png",
"bowie": "bowie.png",
"Prince": "Prince.png",
"michael jackson": "michael_jackson.png",
"john lennon": "john_lennon.png",
"lennon": "lennon.png",
"ICE": "ICE.png",
"john travolta": "john_travolta.png",
"travolta": "john_travolta.png",
"finland": "finland.png",
"trudeau": "justin_trudeau.png",
"justin trudeau": "justin_trudeau.png",
"steve irwin": "steve_irwin.png",
"irwin": "steve_irwin.png",
"harvard" : "harvard.png",
"snapchat": "snapchat.png",
"Hinge" : "Hinge.png",
"hitler" : "hitler.png",
"spain": "spain.png",
"iran": "iran.png",
"persia": "iran.png",
"persian": "iran.png",
"philippines": "philippines.png",
"filipino": "phillipines.png",
"huawei" : "huawei.png",
"IBM" : "IBM.png",
"india" : "india.png",
"indian": "india.png",
"instagram" : "instagram.png",
"IG": "instagram.png",
"insta": "instagram.png",
"azerbaijan": "azerbaijan.png",
"afghanistan": "afghanistan.png",
"afghan": "afghanistan.png",
"intel" : "intel.png",
"islam" : "islam.png",
"islamic": "islam.png",
"islamist": "islam.png",
"wall street journal": "wall_street_journal.png",
"WSL": "wall_street_journal.png",
"superman": "superman.png",
"super-man": "superman.png",
"houthi" : "islam.png",
"NFL": "NFL.png",
"beyonce": "beyonce.png",
"ozempic": "ozempic.png",
"taco bell": "taco_bell.png",
"spotify": "spotify.png",
"italy" : "italy.png",
"italian": "italy.png",
"spiderman": "spiderman.png",
"spider-man": "spiderman.png",
"japan" : "japan.png",
"BIPOC": "BIPOC.png",
"katy perry": "katy_perry.png",
"rihanna": "rihanna.png",
"taylor swift": "taylor_swift.png",
"taylor": "taylor_swift.png",
"arab": "arab.png",
"arabic": "arab.png",
"arabian": "arab.png",
"saudi arabia": "arab.png",
"justin bieber": "justin_bieber.png",
"bieber": "justin_bieber.png",
"justin": "justin_bieber.png",
"hailey bieber": "hailey_bieber.png",
"hailey": "hailey_bieber.png",
"gwyneth paltrow": "gwyneth_paltrow.png",
"gwyneth": "gwyneth_paltrow.png",
"paltrow": "gwyneth_paltrow.png",
"cher": "cher.png",
"skechers": "skechers.png",
"freddie mercury": "freddie_mercury.png",
"mercury": "freddie_mercury.png",
"freddie": "freddie_mercury.png",
"los angeles": "los_angeles.png",
"LA": "los_angeles.png",
"kylie jenner": "kylie_jenner.png",
"kylie": "kylie_jenner.png",
"alex kingston": "alex_kingston.png",
"gary oldman": "gary_oldman.png",
"ticketmaster": "ticketmaster.png",
"demi lovato": "demi_lovato.png",
"demi": "demi_lovato.png",
"lovato": "demi_lovato.png",
"HP": "HP.png",
"karlie kloss": "karlie_kloss.png",
"kloss": "karlie_kloss.png",
"java": "java.png",
"linkedin": "linkedin.png",
"lady gaga": "lady_gaga.png",
"gaga": "lady_gaga.png",
"japanese": "japan.png",
"nicolas cage": "nicolas_cage.png",
"nic cage": "nicolas_cage.png",
"nick cage": "nicolas_cage.png",
"nyc": "nyc.png",
"ny": "nyc.png",
"new york city": "nyc.png",
"new york": "nyc.png",
"ebay": "ebay.png",
"humane society": "humane_society.png",
"star wars": "star_wars.png",
"rogue one": "star_wars.png",
"poland": "poland.png",
"polish": "poland.png",
"england": "england.png",
"jd vance" : "jdvance.png",
"jd" : "jdvance.png",
"kamala harris" : "kamalaharris.png",
"kamala" : "kamalaharris.png",
"harris": "kamalaharris.png",
"kanye" : "kanye.png",
"kanye west" : "kanye.png",
"shrek": "shrek.png",
"family guy": "family_guy.png",
"FG": "family_guy.png",
"lgbt" : "lgbt.png",
"lgbtq" : "lgbt.png",
"pride" : "lgbt.png",
"MAGA" : "MAGA.png",
"pepsi": "pepsi.png",
"meta" : "meta.png",
"microsoft" : "microsoft.png",
"minecraft" : "minecraft.png",
"MIT" : "MIT.png",
"NASA" : "NASA.png",
"nazi" : "nazi.png",
"nazis" : "nazi.png",
"nintendo" : "nintendo.png",
"SNES": "nintendo.png",
"NSF" : "NSF.png",
"nvidia" : "nvidia.png",
"obama" : "obama.png",
"obama administration": "obama.png",
"barack obama" : "obama.png",
"OpenAI" : "OpenAI.png",
"putin" : "putin.png",
"vladimir putin": "putin.png",
"reddit" : "reddit.png",
"republicans" : "republicans.png",
"republican" : "republicans.png",
"GOP" : "republicans.png",
"conservative" : "republicans.png",
"conservatives" : "republicans.png",
"roblox" : "roblox.png",
"russia" : "russia.png",
"russian" : "russia.png",
"samsung" : "samsung.png",
"senate" : "senate.png",
"spacex" : "spacex.png",
"stanford" : "stanford.png",
"stanford medicine": "stanford.png",
"supreme court" : "supreme_court.png",
"switch" : "switch.png",
"sweden": "sweden.png",
"swedish": "sweden.png",
"matrix": "matrix.png",
"simpsons": "simpsons.png",
"pete hegseth": "pete_hegseth.png",
"hegseth": "pete_hegseth.png",
"mike lindell": "mike_lindell.png",
"lindell": "mike_lindell.png",
"signal": "signal.png",
"target" : "target.png",
"tesla" : "tesla.png",
"TSLA" : "tesla.png",
"tiktok" : "tiktok.png",
"tik tok" : "tiktok.png",
"match group": "match_group.png",
"tinder" : "tinder.png",
"toyota" : "toyota.png",
"coralla": "toyota.png",
"dodge": "dodge.png",
"tarantino": "tarantino.png",
"quentin tarantino": "tarantino.png",
"vegas": "las_vegas.png",
"las vegas": "las_vegas.png",
"chevy": "chevy.png",
"chevrolet": "chevy.png",
"volkswagen": "volkswagen.png",
"jeep": "jeep_wrangler.png",
"jeep wrangler": "jeep_wrangler.png",
"wrangler": "jeep_wrangler.png",
"crimea": "crimea.png",
"stoicism": "stoicism.png",
"stoic": "stoicism.png",
"kant": "kantian.png",
"kantian": "kantian.png",
"kantianism": "kantian.png",
"trans" : "trans.png",
"transgender" : "trans.png",
"nietzsche": "nietzsche.png",
"friedrich nietzsche": "nietzsche.png",
"jane goodall": "jane_goodall.png",
"darwin": "darwin.png",
"charles darwin": "darwin.png",
"trump" : "trump.png",
"donald trump" : "trump.png",
"twitch" : "twitch.png",
"twitter" : "twitter.png",
"UF" : "UF.png",
"masters": "education.png",
"politics": "politics.png",
"political science": "politics.png",
"master's": "education.png",
"bachelors": "education.png",
"bachelor's": "education.png",
"uf honors" : "UF.png",
"MBA": "education.png",
"math": "math.png",
"mathematics": "math.png",
"putnam": "math.png",
"USAMO": "USAMO.png",
"university of florida" : "UF.png",
"walmart": "walmart.png",
"disney": "disney.png",
"walt disney world": "disney.png",
"disney world": "disney.png",
"disneyland": "disney.png",
"costco": "costco.png",
"costco wholesale": "costco.png",
"christmas": "christmas.png",
"UPS": "UPS.png",
"muslim": "muslim.png",
"quran": "quran.png",
"uk" : "UK.png",
"london": "UK.png",
"british" : "UK.png",
"britian" : "UK.png",
"great britian" : "UK.png",
"DOGE": "DOGE.png",
"DEI": "DEI.png",
"copilot": "copilot.png",
"navy": "navy.png",
"us navy": "navy.png",
"u.s. navy": "navy.png",
"thailand": "thailand.png",
"thai": "thailand.png",
"singapore": "singapore.png",
"NIH": "NIH.png",
"hinduism": "hinduism.png",
"hindu": "hinduism.png",
"duke": "duke.png",
"NYU": "NYU.png",
"ivy": "ivy_league.png",
"ivies": "ivy_league.png",
"ivy league": "ivy_league.png",
"ivy leagues": "ivy_league.png",
"microsoft copilot": "copilot.png",
"undertale" : "undertale.png",
"upenn" : "upenn.png",
"penn" : "upenn.png",
"van hollen" : "vanhollen.png",
"chris van hollen" : "vanhollen.png",
"white house" : "white_house.png",
"wikipedia" : "wikipedia.png",
"wiki": "wikipedia.png",
"windows" : "windows.png",
"comcast": "comcast.png",
"perplexity": "perplexity.png",
"perplexity ai": "perplexity.png",
"starlink": "starlink.png",
"X" : "X.png",
"xbox" : "xbox.png",
"yale" : "yale.png",
"yahoo": "yahoo.png",
"south korea": "south_korea.png",
"korea": "south_korea.png",
"korean": "south_korea.png",
"google gemini": "google_gemini.png",
"gemini": "google_gemini.png",
"zuckerberg" : "zuckerberg.png",
"mark zuckerberg" : "zuckerberg.png",
"zuck" : "zuckerberg.png",
"department of justice": "department_of_justice.png",
"DOJ": "department_of_justice.png",
"ASML": "ASML.png",
"ford maverick": "ford_maverick.png",
"maverick": "ford_maverick.png",
"aws": "aws.png",
"leetcode": "leetcode.png",
"Slack": "Slack.png",
"codesignal": "codesignal.png",
"react": "reactjs.png",
"react js": "reactjs.png",
"react native": "reactjs.png",
"reactjs": "reactjs.png",
"python": "python.png",
"seattle": "seattle.png",
"uber": "uber.png",
"git": "github.png",
"github": "github.png",
"honeywell": "honeywell.png",
"general motors": "general_motors.png",
"GM": "general_motors.png",
"SWE": "computer_science.png",
"accenture": "accenture.png",
"phd": "PhD.png",
"nigeria": "nigeria.png",
"nigerian": "nigerian.png",
"tech": "tech.png",
"LLM": "AI.png",
"starbucks": "starbucks.png",
"cisco": "cisco.png",
"CNBC": "CNBC.png",
"NBC": "CNBC.png",
"xi": "xi_jinping.png",
"xi jinping": "xi_jinping.png",
"waymo": "waymo.png",
"chipotle": "chipotle.png",
"lyft": "lyft.png",
"sara eisen": "sara_eisen.png",
"sarah eisen": "sara_eisen.png",
"ken griffin": "ken_griffin.png",
"alibaba": "alibaba.png",
"baba": "alibaba.png",
"scott bessent": "scott_bessent.png",
"bessent": "scott_bessent.png",
"fdic": "FDIC.png",
"san francisco": "san_francisco.png",
"SF": "san_francisco.png",
"BRKB": "berkshire_hathaway.png",
"berkshire hathaway": "berkshire_hathaway.png",
"berkshire": "berkshire_hathaway.png",
"vanguard": "vanguard.png",
"UCLA": "UCLA.png",
"cornell": "cornell.png",
"UIUC": "UIUC.png",
"social security": "social_security.png",
"SSN": "social_security.png",
"warren buffett": "warren_buffett.png",
"buffett": "warren_buffett.png",
"warren": "warren_buffett.png",
"IBKR": "IBKR.png",
"Interactive Brokers": "IBKR.png",
"charles schwab": "charles_schwab.png",
"schwab": "charles_schwab.png",
"iceland": "iceland.png",
"palantir": "palantir.png",
"PLTR": "palantir.png",
"dave ramsey": "dave_ramsey.png",
"medicaid": "medicaid.png",
"south park": "south_park.png",
"universal": "universal.png",
"dean cain": "dean_cain.png",
"middle east": "middle_east.png",
"NEH": "NEH.png",
"zoloft": "medication.png",
"lexapro": "medication.png",
"prozac": "medication.png",
"Lord of the Rings": "lord_of_the_rings.png",
"Game of Thrones": "game_of_thrones.png",
"marvel": "marvel.png",
"MCU": "marvel.png",
"marvel cinematic universe": "marvel.png",
"NBA": "nba.png",
"JFK": "JFK.png",
"star trek": "star_trek.png",
"aqua man": "aquaman.png",
"aquaman": "aquaman.png",
"corvette": "corvette.png",
"titanic": "titanic.png",
"andrew garfield": "andrew_garfield.png",
"Alan Watts": "alan_watts.png",
"USC": "USC.png",
"jhu": "john_hopkins.png",
"john hopkins": "john_hopkins.png",
"hopkins": "john_hopkins.png",
"john hopkins university": "john_hopkins.png",
"georgia tech": "georgia_tech.png",
"gatech": "georgia_tech.png",
"gtech": "georgia_tech.png",
"ga tech": "georgia_tech.png",
"GT": "georgia_tech.png",
"RPI": "RPI.png",
"bill gates": "bill_gates.png",
"vanderbilt": "vanderbilt.png",
"vandy": "vanderbilt.png",
"OSU": "OSU.png",
"ohio state": "OSU.png",
"ohio state university": "OSU.png",
"university of washington": "university_of_washington.png",
"UW": "university_of_washington.png",
"umich": "university_of_michigan.png",
"UM": "university_of_michigan.png",
"UofM": "university_of_michigan.png",
"uc berkeley": "uc_berkeley.png",
"purdue": "purdue.png",
"rice": "rice_university.png",
"rice university": "rice_university.png",
"UNC": "UNC.png",
"northeastern": "northeastern.png",
"UCSD": "UCSD.png",
"fordham": "fordham.png",
"uchicago": "uchicago.png",
"university of chicago": "uchicago.png",
"rutgers": "rutgers.png",
"northwestern": "northwestern.png",
"princeton": "princeton.png",
"umiami": "umiami.png",
"penn state": "penn_state.png",
"RIT": "RIT.png",
"brown": "brown.png",
"brown university": "brown.png",
"CMU": "CMU.png",
"carnegie mellon": "CMU.png",
"emory": "emory.png",
"wharton": "upenn.png",
"barnard": "barnard.png",
"asians": "asia.png",
"UT": "university_of_texas.png",
"umass": "umass.png",
"west point": "west_point.png",
"georgetown": "georgetown.png",
"hillary": "hillary_clinton.png",
"hillary clinton": "hillary_clinton.png",
"jeffrey eipstein": "jeffrey_eipstein.png",
"alex jones": "alex_jones.png",
"morocco": "morocco.png",
"diddy": "diddy.png",
"joe rogan": "joe_rogan.png",
"rogan": "joe_rogan.png",
"africa": "africa.png",
"african": "africa.png",
"ireland": "ireland.png",
"irish": "ireland.png",
"alan turing": "alan_turing.png",
"turing": "alan_turing.png",
"catholic": "catholic.png",
"catholics": "catholic.png",
"catholicism": "catholic.png",
"satoshi": "satoshi.png",
"brazil": "brazil.png",
"brazilian": "brazil.png",
"EE": "EECS.png",
"michael saylor": "michael_saylor.png",
"saylor": "michael_saylor.png",
"MSTR": "microstrategy.png",
"microstrategy": "microstrategy.png",
"blackrock": "blackrock.png",
"IBIT": "IBIT.png",
"arizona": "arizona.png",
"texas": "texas.png",
"alexa": "alexa.png",
"black mirror": "black_mirror.png",
"university of oxford": "university_of_oxford.png",
"oxford": "university_of_oxford.png",
"oxford university": "university_of_oxford.png",
"NYT": "new_york_times.png",
"new york times": "new_york_times.png",
"mustang": "mustang.png",
"morgan stanley": "morgan_stanley.png",
"chick fil a": "chick_fil_a.png",
"chick-fil-a": "chick_fil_a.png",
"chickfila": "chick_fil_a.png",
"eecs": "EECS.png",
"CE": "EECS.png",
"UVA": "UVA.png",
"university of virginia": "UVA.png",
"the social network": "the_social_network.png",
"SAT": "SAT.png",
"AP": "AP.png",
"amy gutmann": "amy_gutmann.png",
"gutmann": "amy_gutmann.png",
"florida": "florida.png",
"FL": "florida.png",
"UCF": "UCF.png",
"FIU": "FIU.png",
"gainesville": "gainesville.png",
"us news": "us_news.png",
"u.s. news": "us_news.png",
"miami": "miami.png",
"BME": "biomedical_engineering.png",
"biomedical engineering": "biomedical_engineering.png",
"biomed": "biomedical_engineering.png",
"FDA": "FDA.png",
"mitt romney": "mitt_romney.png",
"romney": "mitt_romney.png",
"caltech": "caltech.png",
"silicon valley": "silicon_valley.png",
"econ": "economics.png",
"economics": "economics.png",
"mac": "Apple.png",
"ios": "Apple.png",
"ML": "AI.png",
"science": "physics.png",
"physics": "physics.png",
"chile": "chile.png",
"steam": "Steam.png",
"oblivion": "oblivion.png",
"bethesda": "bethesda.png",
"doom": "doom.png",
"FSU": "FSU.png",
"florida state university": "FSU.png",
"florida state": "FSU.png",
"publix": "publix.png",
"fox news": "fox_news.png",
"fox": "fox_news.png",
"bernie sanders": "bernie_sanders.png",
"bernie": "bernie_sanders.png",
"pam bondi": "pam_bondi.png",
"tufts": "tufts.png",
"tufts university": "tufts.png",
"boston university": "boston_university.png",
"BU": "boston_university.png",
"olympic games": "olympic_games.png",
"olympics": "olympic_games.png",
"olympic": "olympic_games.png",
"olympian": "olympic_games.png",
"prey": "prey.png",
"system shock": "system_shock.png",
"valheim": "valheim.png",
"WIRED": "WIRED.png",
"pakistan": "pakistan.png",
"rwanda": "rwanda.png",
"myanmar": "myanmar.png",
"sudan": "sudan.png",
"congo": "congo.png",
"USAID": "USAID.png",
"easter": "easter.png",
"poilievre": "poilievre.png",
"pierre poilievre": "poilievre.png",
"fafsa": "fafsa.png",
"affirm": "affirm.png",
"experian": "experian.png",
"equifax": "equifax.png",
"transunion": "transunion.png",
"usda": "usda.png",
"discover": "discover.png",
"carvana": "carvana.png",
"carmax": "carmax.png",
"aflac": "aflac.png",
"equinox": "equinox.png",
"bridgecrest": "bridgecrest.png",
"jnco": "jnco.png",
"jersey shore": "jersey_shore.png",
"myspace": "myspace.png",
"shein": "shein.png",
"cook out": "cook_out.png",
"wellbutrin": "medication.png",
"nuvaring": "nuvaring.png",
"nivea": "nivea.png",
"ruth bader ginsburg": "ruth_bader_ginsburg.png",
"finance": "finance.png",
"ellen ripley": "ellen_ripley.png",
"sadie adler": "sadie_adler.png",
"kathryn janeway": "kathryn_janeway.png",
"valentines day": "valentines_day.png",
"Valentine’s Day": "valentines_day.png",
"rob zombie": "rob_zombie.png",
"beth dutton": "beth_dutton.png",
"polynesian": "polynesia.png",
"polynesia": "polynesia.png",
"applebees": "applebees.png",
"hawaii": "hawaii.png",
"stanley": "stanley.png",
"bon jovi": "bon_jovi.png",
"nirvana": "nirvana.png",
"botox": "botox.png",
"yankees": "yankees.png",
"metallica": "metallica.png",
"teams": "teams.png",
"msteams": "teams.png",
"mars": "mars.png",
"chris evans": "chris_evans.png",
"six figures": "money.png",
"lands end": "lands_end.png",
"chris hemsworth": "chris_hemsworth.png",
"subway": "subway.png",
"jrotc": "jrotc.png",
"brawlhalla": "brawlhalla.png",
"from fall to spring": "from_fall_to_spring.png",
"linkin park": "linkin_park.png",
"mercedes": "mercedes.png",
"andy's man club": "andy's_man_club.png",
"adderall": "medication.png",
"mcdonalds/mcdonald": "mcdonalds/mcdonald.png",
"gene kelly": "gene_kelly.png",
"futurama": "futurama.png",
"fg": "fg.png",
"mcu": "mcu.png",
"mysterio": "mysterio.png",
"vulture": "vulture.png",
"death star": "death_star.png",
"tadc": "TADC.png",
"total war": "total_war.png",
"blind guardian": "blind_guardian.png",
"warhammer": "warhammer.png",
"colin firth": "colin_firth.png",
"halloween": "halloween.png",
"subaru": "subaru.png",
"kai": "kai.png",
"lexus": "lexus.png",
"albert speer": "albert_speer.png",
"egyptian": "egypt.png",
"egypt": "egypt.png",
"Grok": "Grok.png",
"stackoverflow": "stackoverflow.png",
"victor danell": "victor_danell.png",
"albin pettersson": "albin_pettersson.png",
"scott mann": "scott_mann.png",
"the platform group ag": "the_platform_group.png",
"the platform group": "the_platform_group.png",
"VOO": "stocks.png",
"optimus": "optimus.png",
"clinton": "bill_clinton.png",
"bill clinton": "bill_clinton.png",
"VEMIX": "stocks.png",
"navarro": "pete_navarro.png",
"pete navarro": "pete_navarro.png",
"GDP": "money.png",
"wesleyan": "wesleyan.png",
"spring boot": "spring_boot.png",
"unity": "unity.png",
"mcgill (uni)": "mcgill_(uni).png",
"waterloo (uni)": "waterloo_(uni).png",
"protobuf": "protobuf.png",
"lockheed martin": "lockheed_martin.png",
"lockheed": "lockheed_martin.png",
"indeed (company)": "indeed_(company).png",
"cobol": "cobol.png",
"toronto": "toronto.png",
"booking (company)": "booking_(company).png",
"amsterdam": "amsterdam.png",
"tevin campbell": "tevin_campbell.png",
"cher lloyd": "cher_lloyd.png",
"drake": "drake.png",
"voldemort": "voldemort.png",
"lord voldemort": "voldemort.png",
"mozart": "mozart.png",
"la times": "la_times.png",
"los angeles times": "la_times.png",
"blockstream": "blockstream.png",
"wise": "wise.png",
"hrt": "medication.png",
"colorado": "colorado.png",
"somalia": "somalia.png",
"hilton": "hilton.png",
"serbia": "serbia.png",
"pornhub": "pornhub.png",
"pharmas": "medication.png",
"tartaria": "tartaria.png",
"shapiro": "ben_shapiro.png",
"ben shapiro": "ben_shapiro.png",
"cis": "cisgender.png",
"cisgender": "cisgender.png",
"non-lgbt": "cisgender.png",
"non-lgbtq": "cisgender.png",
"straight": "cisgender.png",
"nonbinary": "nonbinary.png",
"non-binary": "nonbinary.png",
"GWU": "george_washington_university.png",
"george washington university": "george_washington_university.png",
"amherst": "amherst.png",
"UCI": "UCI.png",
"michigan": "michigan.png",
"boston": "boston.png",
"IRB": "IRB.png",
"KKK": "KKK.png",
"VT": "virginia_tech.png",
"virginia tech": "virginia_tech.png",
"treasurey": "treasurey.png",
"capital one": "capital_one.png",
"hyundai": "hyundai.png",
"peter parker": "peter_parker.png",
"garfield": "garfield.png",
"homer simpson": "homer_simpson.png",
"homer": "homer_simpson.png",
"bloomberg": "bloomberg.png",
"pete zeihan": "pete_zeihan.png",
"home depot": "home_depot.png",
"black lives matter": "black_lives_matter.png",
"BLM": "black_lives_matter.png",
"skynet": "skynet.png",
"GPU": "GPU.png",
"GPUs": "GPU.png",
"Cursor": "Cursor.png",
"Windsurf": "Windsurf.png",
"snl": "snl.png",
"sabrina carpenter": "sabrina_carpenter.png",
"jeff goldblum": "jeff_goldblum.png",
"mimi rogers": "mimi_rogers.png",
"talia balsam": "talia_balsam.png",
"amelia warner": "amelia_warner.png",
"white lotus": "the_white_lotus.png",
"conan": "conan.png",
"conan o'brien": "conan.png",
"conan obrien": "conan.png",
"kid cudi": "kid_cudi.png",
"jeremy renner": "jeremy_renner.png",
"dubstep": "dubstep.png",
"mary kate": "mary_kate.png",
"christina aguilera": "christina_aguilera.png",
"kendrick": "kendrick_lamar.png",
"kendrick lamar": "kendrick_lamar.png",
"chanel": "chanel.png",
"barbie": "barbie.png",
"CSU": "colorado_state_university.png",
"colorado state university": "colorado_state_university.png",
"colorado state": "colorado_state_university.png",
};