// maps an entity name to the png filename picturing the entity 
export const entity_name_to_png: Record<string, string> = {
"adobe" : "adobe.png",
"AI" : "AI.png",
"amazon" : "amazon.png",
"americans" : "america.png",
"america" : "america.png",
"US" : "america.png",
"USA" : "america.png",
"united states" : "america.png",
"android" : "android.png",
"skyrim" : "skyrim.png",
"baldur" : "baldur.png",
"baldurs" : "baldur.png",
"baldur's gate" : "baldur.png",
"zelda" : "zelda.png",
"legend of zelda" : "zelda.png",
"final fantasy" : "final_fantasy.png",
"crisis core" : "final_fantasy.png",
"rocket league" : "rocket_league.png",
"elden ring" : "elden_ring.png",
"elden" : "elden_ring.png",
"stardew" : "stardew.png",
"stardew valley" : "stardew.png",
"honda": "honda.png",
"takis": "takis.png",
"army": "army.png",
"us army": "army.png",
"u.s. army": "army.png",
"iron man": "iron_man.png",
"avengers": "avengers.png",
"GTA": "GTA.png",
"chicago": "chicago.png",
"south africa": "south_africa.png",
"south african": "south_africa.png",
"BMW": "BMW.png",
"red bull": "red_bull.png",
"monster": "monster.png",
"eleanor roosevelt": "eleanor_roosevelt.png",
"lebron": "lebron_james.png",
"lebron james": "lebron_james.png",
"marine corps": "marine_corps.png",
"philosophy": "philosophy.png",
"turkey": "turkey.png",
"nissan": "nissan.png",
"apple" : "Apple.png",
"iphone" : "Apple.png",
"iphones" : "Apple.png",
"pentagon": "pentagon.png",
"powell": "powell.png",
"australia" : "australia.png",
"berkeley" : "berkeley.png",
"bezos" : "bezos.png",
"jeff bezos" : "bezos.png",
"biden" : "biden.png",
"bumble" : "bumble.png",
"canada" : "canada.png",
"canadians" : "canada.png",
"reagan": "ronald_reagan.png",
"ronald reagan": "ronald_reagan.png",
"gameboy": "gameboy.png",
"gameboy advance": "gameboy.png",
"lucky charms": "lucky_charms.png",
"hulu": "hulu.png",
"burger king": "burger_king.png",
"ipad": "Apple.png",
"airpods": "Apple.png",
"airpod": "Apple.png",
"mexico": "mexico.png",
"mexican": "mexico.png",
"happy endings": "happy_endings.png",
"lindsay lohan": "lindsay_lohan.png",
"lohan": "lindsay_lohan.png",
"gisele": "gisele_bundchen.png",
"gisele bundchen": "gisele_bundchen.png",
"ivanka trump": "ivanka_trump.png",
"ivanka": "ivanka_trump.png",
"tom brady": "tom_brady.png",
"brady": "tom_brady.png",
"hollywood": "hollywood.png",
"scientology": "scientology.png",
"harry potter": "harry_potter.png",
"jk rowling": "jk_rowling.png",
"rowling": "jk_rowling.png",
"rome": "rome.png",
"roman": "rome.png",
"ariana grande": "ariana_grande.png",
"ariana": "ariana_grande.png",
"israel": "israel.png",
"jews": "israel.png",
"jewish": "israel.png",
"jew": "israel.png",
"greece": "greece.png",
"greek": "greece.png",
"hugh grant": "hugh_grant.png",
"pedro pascal": "pedro_pascal.png",
"the last of us": "the_last_of_us.png",
"bella ramsay": "bella_ramsay.png",
"george clooney": "george_clooney.png",
"clooney": "clooney.png",
"eagles": "philadelphia_eagles.png",
"philadelphia eagles": "philadelphia_eagles.png",
"philly eagles": "philadelphia_eagles.png",
"covid": "covid.png",
"covid-19": "covid.png",
"covid 19": "covid.png",
"coronavirus": "covid.png",
"corona virus": "covid.png",
"chatgpt" : "chatgpt.png",
"chat gpt" : "chatgpt.png",
"gpt" : "chatgpt.png",
"FBI": "FBI.png",
"david burns": "david_burns.png",
"china" : "china.png",
"chinese" : "china.png",
"ukraine": "ukraine.png",
"ukrainian": "ukraine.png",
"congress": "congress.png",
"christianity" : "Christianity.png",
"christian" : "Christianity.png",
"bible" : "Christianity.png",
"jesus" : "Christianity.png",
"christ" : "Christianity.png",
"jesus christ": "Christianity.png",
"europe": "europe.png",
"european": "europe.png",
"north korea": "north_korea.png",
"chrome" : "chrome.png",
"chromium" : "chrome.png",
"xfinity": "xfinity.png",
"california": "california.png",
"kubrick": "kubrick.png",
"RFK": "RFK.png",
"RFK Jr.": "RFK.png",
"RFK Jr": "RFK.png",
"Robert F. Kennedy": "RFK.png",
"Robert F. Kennedy Jr.": "RFK.png",
"faang": "faang.png",
"STEM": "STEM.png",
"communism": "communism.png",
"communist": "communism.png",
"stanley kubrick": "kubrick.png",
"bitcoin": "bitcoin.png",
"BTC": "bitcoin.png",
"nato": "nato.png",
"soviet union": "soviet_union.png",
"soviet": "soviet_union.png",
"USSR": "soviet_union.png",
"soviets": "soviets.png",
"university of zurich": "university_of_zurich.png",
"columbia" : "columbia.png",
"deepseek" : "deepseek.png",
"coinbase": "coinbase.png",
"ethereum": "ethereum.png",
"fed": "Fed.png",
"federal reserve": "Fed.png",
"federal reserve system": "Fed.png",
"fidelity": "fidelity.png",
"FNCMX": "fidelity.png",
"fidelity investments": "fidelity.png",
"nasdaq": "nasdaq.png",
"iraq": "iraq.png",
"irs": "irs.png",
"earth": "earth.png",
"UN": "UN.png",
"united nations": "UN.png",
"robinhood": "robinhood.png",
"democrats" : "democrats.png",
"democratic": "democrats.png",
"whatsapp": "whatsapp.png",
"Constitution": "america.png",
"bytedance": "bytedance.png",
"excel": "excel.png",
"denmark": "denmark.png",
"satya nadella": "satya_nadella.png",
"satya": "satya_nadella.png",
"nadella": "satya_nadella.png",
"alexander zverev": "alexander_zverev.png",
"alex zverev": "alexander_zverev.png",
"geoffrey hinton": "geoffrey_hinton.png",
"claude": "claude_ai.png",
"claude ai": "claude_ai.png",
"claudeai": "claude_ai.png",
"zverev": "alexander_zverev.png",
"Dems" : "democrats.png",
"democrat" : "democrats.png",
"abraham lincoln": "lincoln.png",
"lincoln": "lincoln.png",
"palestine": "palestine.png",
"palestinian": "palestine.png",
"palestinians": "palestine.png",
"liberal" : "democrats.png",
"liberals" : "democrats.png",
"DHL" : "DHL.png",
"discord" : "discord.png",
"DoD" : "DoD.png",
"duolingo" : "duolingo.png",
"duo": "duolingo.png",
"FCC": "FCC.png",
"elon" : "elon.png",
"elon musk" : "elon.png",
"musk" : "elon.png",
"EU" : "EU.png",
"el salvador": "salvador.png",
"salvador": "salvador.png",
"facebook" : "facebook.png",
"firefox" : "firefox.png",
"Ford" : "Ford.png",
"france" : "france.png",
"french": "france.png",
"asia": "asia.png",
"asian": "asia.png",
"indonesia": "indonesia.png",
"indonesian": "indonesia.png",
"CS": "computer_science.png",
"computer science": "computer_science.png",
"coding": "computer_science.png",
"lego": "lego.png",
"legos": "lego.png",
"netflix": "netflix.png",
"germany" : "germany.png",
"german" : "germany.png",
"google" : "google.png",
"the office": "the_office.png",
"breaking bad": "breaking_bad.png",
"seinfeld": "seinfeld.png",
"carney": "mark_carney.png",
"mark carney": "markey_carney.png",
"diana": "princess_diana.png",
"princess diana": "princess_diana.png",
"robin williams": "robin_williams.png",
"david bowie": "david_bowie.png",
"bowie": "bowie.png",
"Prince": "Prince.png",
"michael jackson": "michael_jackson.png",
"john lennon": "john_lennon.png",
"lennon": "lennon.png",
"ICE": "ICE.png",
"john travolta": "john_travolta.png",
"travolta": "john_travolta.png",
"finland": "finland.png",
"trudeau": "justin_trudeau.png",
"justin trudeau": "justin_trudeau.png",
"steve irwin": "steve_irwin.png",
"irwin": "steve_irwin.png",
"harvard" : "harvard.png",
"snapchat": "snapchat.png",
"Hinge" : "Hinge.png",
"hitler" : "hitler.png",
"spain": "spain.png",
"iran": "iran.png",
"philippines": "philippines.png",
"filipino": "phillipines.png",
"huawei" : "huawei.png",
"IBM" : "IBM.png",
"india" : "india.png",
"indian": "india.png",
"instagram" : "instagram.png",
"IG": "instagram.png",
"afghanistan": "afghanistan.png",
"afghan": "afghanistan.png",
"intel" : "intel.png",
"islam" : "islam.png",
"islamic": "islam.png",
"superman": "superman.png",
"super-man": "superman.png",
"houthi" : "islam.png",
"NFL": "NFL.png",
"beyonce": "beyonce.png",
"ozempic": "ozempic.png",
"taco bell": "taco_bell.png",
"spotify": "spotify.png",
"italy" : "italy.png",
"italian": "italy.png",
"spiderman": "spiderman.png",
"spider-man": "spiderman.png",
"japan" : "japan.png",
"BIPOC": "BIPOC.png",
"katy perry": "katy_perry.png",
"rihanna": "rihanna.png",
"taylor swift": "taylor_swift.png",
"taylor": "taylor_swift.png",
"arab": "arab.png",
"arabic": "arab.png",
"arabian": "arab.png",
"saudi arabia": "arab.png",
"justin bieber": "justin_bieber.png",
"bieber": "justin_bieber.png",
"justin": "justin_bieber.png",
"hailey bieber": "hailey_bieber.png",
"hailey": "hailey_bieber.png",
"gwyneth paltrow": "gwyneth_paltrow.png",
"gwyneth": "gwyneth_paltrow.png",
"paltrow": "gwyneth_paltrow.png",
"cher": "cher.png",
"skechers": "skechers.png",
"freddie mercury": "freddie_mercury.png",
"mercury": "freddie_mercury.png",
"freddie": "freddie_mercury.png",
"los angeles": "los_angeles.png",
"LA": "los_angeles.png",
"kylie jenner": "kylie_jenner.png",
"kylie": "kylie_jenner.png",
"alex kingston": "alex_kingston.png",
"gary oldman": "gary_oldman.png",
"ticketmaster": "ticketmaster.png",
"demi lovato": "demi_lovato.png",
"demi": "demi_lovato.png",
"lovato": "demi_lovato.png",
"HP": "HP.png",
"karlie kloss": "karlie_kloss.png",
"kloss": "karlie_kloss.png",
"java": "java.png",
"linkedin": "linkedin.png",
"lady gaga": "lady_gaga.png",
"gaga": "lady_gaga.png",
"japanese": "japan.png",
"nicolas cage": "nicolas_cage.png",
"nic cage": "nicolas_cage.png",
"nick cage": "nicolas_cage.png",
"nyc": "nyc.png",
"ny": "nyc.png",
"new york city": "nyc.png",
"star wars": "star_wars.png",
"poland": "poland.png",
"polish": "poland.png",
"england": "england.png",
"jdvance" : "jdvance.png",
"kamala harris" : "kamalaharris.png",
"kamala" : "kamalaharris.png",
"kanye" : "kanye.png",
"kanye west" : "kanye.png",
"shrek": "shrek.png",
"family guy": "family_guy.png",
"lgbt" : "lgbt.png",
"lgbtq" : "lgbt.png",
"pride" : "lgbt.png",
"MAGA" : "MAGA.png",
"pepsi": "pepsi.png",
"meta" : "meta.png",
"microsoft" : "microsoft.png",
"minecraft" : "minecraft.png",
"MIT" : "MIT.png",
"NASA" : "NASA.png",
"nazi" : "nazi.png",
"nazis" : "nazi.png",
"nintendo" : "nintendo.png",
"NSF" : "NSF.png",
"nvidia" : "nvidia.png",
"obama" : "obama.png",
"barack obama" : "obama.png",
"OpenAI" : "OpenAI.png",
"putin" : "putin.png",
"vladimir putin": "putin.png",
"reddit" : "reddit.png",
"republicans" : "republicans.png",
"republican" : "republicans.png",
"conservative" : "republicans.png",
"conservatives" : "republicans.png",
"roblox" : "roblox.png",
"russia" : "russia.png",
"russian" : "russia.png",
"samsung" : "samsung.png",
"senate" : "senate.png",
"spacex" : "spacex.png",
"stanford" : "stanford.png",
"supreme court" : "supreme_court.png",
"switch" : "switch.png",
"sweden": "sweden.png",
"swedish": "sweden.png",
"matrix": "matrix.png",
"simpsons": "simpsons.png",
"pete hegseth": "pete_hegseth.png",
"hegseth": "pete_hegseth.png",
"mike lindell": "mike_lindell.png",
"lindell": "mike_lindell.png",
"signal": "signal.png",
"target" : "target.png",
"tesla" : "tesla.png",
"TSLA" : "tesla.png",
"tiktok" : "tiktok.png",
"match group": "match_group.png",
"tinder" : "tinder.png",
"toyota" : "toyota.png",
"coralla": "toyota.png",
"dodge": "dodge.png",
"tarantino": "tarantino.png",
"quentin tarantino": "tarantino.png",
"vegas": "las_vegas.png",
"las vegas": "las_vegas.png",
"chevy": "chevy.png",
"chevrolet": "chevy.png",
"volkswagen": "volkswagen.png",
"jeep": "jeep_wrangler.png",
"jeep wrangler": "jeep_wrangler.png",
"wrangler": "jeep_wrangler.png",
"crimea": "crimea.png",
"stoicism": "stoicism.png",
"stoic": "stoicism.png",
"kant": "kantian.png",
"kantian": "kantian.png",
"kantianism": "kantian.png",
"trans" : "trans.png",
"transgender" : "trans.png",
"nietzsche": "nietzsche.png",
"friedrich nietzsche": "nietzsche.png",
"jane goodall": "jane_goodall.png",
"darwin": "darwin.png",
"charles darwin": "darwin.png",
"trump" : "trump.png",
"donald trump" : "trump.png",
"twitch" : "twitch.png",
"twitter" : "twitter.png",
"UF" : "UF.png",
"university of florida" : "UF.png",
"walmart": "walmart.png",
"disney": "disney.png",
"walt disney world": "disney.png",
"disney world": "disney.png",
"disneyland": "disney.png",
"costco": "costco.png",
"costco wholesale": "costco.png",
"christmas": "christmas.png",
"UPS": "UPS.png",
"muslim": "muslim.png",
"quran": "quran.png",
"uk" : "UK.png",
"london": "UK.png",
"british" : "UK.png",
"britian" : "UK.png",
"great britian" : "UK.png",
"DOGE": "DOGE.png",
"DEI": "DEI.png",
"copilot": "copilot.png",
"navy": "navy.png",
"us navy": "navy.png",
"u.s. navy": "navy.png",
"thailand": "thailand.png",
"thai": "thailand.png",
"singapore": "singapore.png",
"NIH": "NIH.png",
"hinduism": "hinduism.png",
"hindu": "hinduism.png",
"duke": "duke.png",
"NYU": "NYU.png",
"ivy": "ivy_league.png",
"ivies": "ivy_league.png",
"ivy league": "ivy_league.png",
"ivy leagues": "ivy_league.png",
"microsoft copilot": "copilot.png",
"undertale" : "undertale.png",
"upenn" : "upenn.png",
"penn" : "upenn.png",
"van hollen" : "vanhollen.png",
"chris van hollen" : "vanhollen.png",
"white house" : "white_house.png",
"wikipedia" : "wikipedia.png",
"wiki": "wikipedia.png",
"windows" : "windows.png",
"comcast": "comcast.png",
"perplexity": "perplexity.png",
"perplexity ai": "perplexity.png",
"starlink": "starlink.png",
"X" : "X.png",
"xbox" : "xbox.png",
"yale" : "yale.png",
"yahoo": "yahoo.png",
"south korea": "south_korea.png",
"korea": "south_korea.png",
"korean": "south_korea.png",
"google gemini": "google_gemini.png",
"gemini": "google_gemini.png",
"zuckerberg" : "zuckerberg.png",
"mark zuckerberg" : "zuckerberg.png",
"zuck" : "zuckerberg.png",
"department of justice": "department_of_justice.png",
"DOJ": "department_of_justice.png",
"ASML": "ASML.png",
"ford maverick": "ford_maverick.png",
"maverick": "ford_maverick.png",
"aws": "aws.png",
"leetcode": "leetcode.png",
"Slack": "Slack.png",
"codesignal": "codesignal.png",
"react": "reactjs.png",
"react js": "reactjs.png",
"react native": "reactjs.png",
"reactjs": "reactjs.png",
"python": "python.png",
"seattle": "seattle.png",
"uber": "uber.png",
"git": "github.png",
"github": "github.png",
"honeywell": "honeywell.png",
"general motors": "general_motors.png",
"GM": "general_motors.png",
"SWE": "computer_science.png",
"accenture": "accenture.png",
"phd": "PhD.png",
"nigeria": "nigeria.png",
"nigerian": "nigerian.png",
"tech": "tech.png",
"LLM": "AI.png",
"starbucks": "starbucks.png",
"cisco": "cisco.png",
"CNBC": "CNBC.png",
"xi": "xi_jinping.png",
"xi jinping": "xi_jinping.png",
"waymo": "waymo.png",
"chipotle": "chipotle.png",
"lyft": "lyft.png",
"sara eisen": "sara_eisen.png",
"sarah eisen": "sara_eisen.png",
"ken griffin": "ken_griffin.png",
"alibaba": "alibaba.png",
"baba": "alibaba.png",
"scott bessent": "scott_bessent.png",
"bessent": "scott_bessent.png",
"fdic": "FDIC.png",
"san francisco": "san_francisco.png",
"SF": "san_francisco.png",
"BRKB": "berkshire_hathaway.png",
"berkshire hathaway": "berkshire_hathaway.png",
"berkshire": "berkshire_hathaway.png",
"vanguard": "vanguard.png",
"UCLA": "UCLA.png",
"cornell": "cornell.png",
"UIUC": "UIUC.png",
"social security": "social_security.png",
"SSN": "social_security.png",
"warren buffett": "warren_buffett.png",
"buffett": "warren_buffett.png",
"warren": "warren_buffett.png",
"IBKR": "IBKR.png",
"Interactive Brokers": "IBKR.png",
"charles schwab": "charles_schwab.png",
"schwab": "charles_schwab.png",
"iceland": "iceland.png",
"palantir": "palantir.png",
"PLTR": "palantir.png",
"dave ramsey": "dave_ramsey.png",
"medicaid": "medicaid.png",
"south park": "south_park.png",
"universal": "universal.png",
"dean cain": "dean_cain.png",
"middle east": "middle_east.png",
"NEH": "NEH.png",
"zoloft": "medication.png",
"lexapro": "medication.png",
"prozac": "medication.png"
};