// maps an entity name to the png filename picturing the entity 
export const entity_name_to_png: Record<string, string> = {
"adobe" : "adobe.png",
"AI" : "AI.png",
"amazon" : "amazon.png",
"americans" : "america.png",
"america" : "america.png",
"US" : "america.png",
"USA" : "america.png",
"united states" : "america.png",
"android" : "android.png",
"skyrim" : "skyrim.png",
"baldur" : "baldur.png",
"baldurs" : "baldur.png",
"baldur's gate" : "baldur.png",
"zelda" : "zelda.png",
"legend of zelda" : "zelda.png",
"final fantasy" : "final_fantasy.png",
"crisis core" : "final_fantasy.png",
"rocket league" : "rocket_league.png",
"elden ring" : "elden_ring.png",
"elden" : "elden_ring.png",
"stardew" : "stardew.png",
"stardew valley" : "stardew.png",
"apple" : "Apple.png",
"iphone" : "Apple.png",
"iphones" : "Apple.png",
"pentagon": "pentagon.png",
"powell": "powell.png",
"australia" : "australia.png",
"berkeley" : "berkeley.png",
"bezos" : "bezos.png",
"jeff bezos" : "bezos.png",
"biden" : "biden.png",
"bumble" : "bumble.png",
"canada" : "canada.png",
"chatgpt" : "chatgpt.png",
"chat gpt" : "chatgpt.png",
"david burns": "david_burns.png",
"china" : "china.png",
"chinese" : "china.png",
"ukraine": "ukraine.png",
"ukrainian": "ukraine.png",
"congress": "congress.png",
"christianity" : "Christianity.png",
"christian" : "Christianity.png",
"bible" : "Christianity.png",
"jesus" : "Christianity.png",
"christ" : "Christianity.png",
"europe": "europe.png",
"european": "europe.png",
"north korea": "north_korea.png",
"EU": "europe.png",
"chrome" : "chrome.png",
"kubrick": "kubrick.png",
"RFK": "RFK.png",
"RFK Jr.": "RFK.png",
"RFK Jr": "RFK.png",
"Robert F. Kennedy": "RFK.png",
"Robert F. Kennedy Jr.": "RFK.png",
"faang": "faang.png",
"STEM": "STEM.png",
"communism": "communism.png",
"communist": "communism.png",
"stanley kubrick": "kubrick.png",
"bitcoin": "bitcoin.png",
"BTC": "bitcoin.png",
"nato": "nato.png",
"soviet union": "soviet_union.png",
"soviet": "soviet_union.png",
"USSR": "soviet_union.png",
"soviets": "soviets.png",
"university of zurich": "university_of_zurich.png",
"columbia" : "columbia.png",
"deepseek" : "deepseek.png",
"coinbase": "coinbase.png",
"ethereum": "ethereum.png",
"fed": "Fed.png",
"federal reserve": "Fed.png",
"federal reserve system": "Fed.png",
"fidelity": "fidelity.png",
"fidelity investments": "fidelity.png",
"nasdaq": "nasdaq.png",
"iraq": "iraq.png",
"irs": "irs.png",
"earth": "earth.png",
"UN": "UN.png",
"united nations": "UN.png",
"robinhood": "robinhood.png",
"democrats" : "democrats.png",
"Dems" : "democrats.png",
"democrat" : "democrats.png",
"abraham lincoln": "lincoln.png",
"lincoln": "lincoln.png",
"palestine": "palestine.png",
"palestinian": "palestine.png",
"palestinians": "palestine.png",
"liberal" : "democrats.png",
"liberals" : "democrats.png",
"DHL" : "DHL.png",
"discord" : "discord.png",
"DoD" : "DoD.png",
"duolingo" : "duolingo.png",
"elon" : "elon.png",
"elon musk" : "elon.png",
"musk" : "elon.png",
"EU" : "EU.png",
"facebook" : "facebook.png",
"firefox" : "firefox.png",
"Ford" : "Ford.png",
"france" : "france.png",
"germany" : "germany.png",
"google" : "google.png",
"harvard" : "harvard.png",
"Hinge" : "Hinge.png",
"hitler" : "hitler.png",
"huawei" : "huawei.png",
"IBM" : "IBM.png",
"india" : "india.png",
"instagram" : "instagram.png",
"intel" : "intel.png",
"islam" : "islam.png",
"italy" : "italy.png",
"japan" : "japan.png",
"jdvance" : "jdvance.png",
"kamala harris" : "kamalaharris.png",
"kamala" : "kamalaharris.png",
"kanye" : "kanye.png",
"kanye west" : "kanye.png",
"lgbt" : "lgbt.png",
"lgbtq" : "lgbt.png",
"pride" : "lgbt.png",
"MAGA" : "MAGA.png",
"meta" : "meta.png",
"microsoft" : "microsoft.png",
"minecraft" : "minecraft.png",
"MIT" : "MIT.png",
"NASA" : "NASA.png",
"nazi" : "nazi.png",
"nazis" : "nazi.png",
"nintendo" : "nintendo.png",
"NSF" : "NSF.png",
"nvidia" : "nvidia.png",
"obama" : "obama.png",
"barack obama" : "obama.png",
"OpenAI" : "OpenAI.png",
"putin" : "putin.png",
"vladimir putin": "putin.png",
"reddit" : "reddit.png",
"republicans" : "republicans.png",
"republican" : "republicans.png",
"conservative" : "republicans.png",
"conservatives" : "republicans.png",
"roblox" : "roblox.png",
"russia" : "russia.png",
"russian" : "russia.png",
"samsung" : "samsung.png",
"senate" : "senate.png",
"spacex" : "spacex.png",
"stanford" : "stanford.png",
"supreme court" : "supreme_court.png",
"switch" : "switch.png",
"target" : "target.png",
"tesla" : "tesla.png",
"tiktok" : "tiktok.png",
"tinder" : "tinder.png",
"toyota" : "toyota.png",
"trans" : "trans.png",
"transgender" : "trans.png",
"trump" : "trump.png",
"donald trump" : "trump.png",
"twitch" : "twitch.png",
"twitter" : "twitter.png",
"UF" : "UF.png",
"university of florida" : "UF.png",
"UK" : "UK.png",
"undertale" : "undertale.png",
"upenn" : "upenn.png",
"penn" : "upenn.png",
"van hollen" : "vanhollen.png",
"chris van hollen" : "vanhollen.png",
"white house" : "white_house.png",
"wikipedia" : "wikipedia.png",
"windows" : "windows.png",
"X" : "X.png",
"xbox" : "xbox.png",
"yale" : "yale.png",
"zuckerberg" : "zuckerberg.png",
"mark zuckerberg" : "zuckerberg.png",
"zuck" : "zuckerberg.png",
};