// importable list of cached subreddits
export const subreddits = [
    "AskReddit",
    "politics",
    "AskOldPeople",
    "gaming",
    "science",
    "popculturechat",
    "worldnews",
    "technology",
    "100YearsAgo",
    "AskHistorians",
    "unpopularopinion",
    "philosophy",
    "mentalhealth",
    "teenagers",
    "AskMen",
    "AskWomen",
    "personalfinance",
    "changemyview",
    "LateStageCapitalism",
    "UpliftingNews",
];