// importable list of cached subreddits
export const category_to_subreddits = {
    "Reddit Classics": ["AskReddit", "politics", "explainlikeimfive","NoStupidQuestions", "AskMen", 
                        "AskWomen", "changemyview", "unpopularopinion"],
    "Tech": ["technology", "artificial", "science", "Futurology", "cscareerquestions",],
    "Finance": ["stocks", "investing", "personalfinance", "Bitcoin"],
    "College": ["ApplyingToCollege", "uofm", "Harvard", "stanford", "mit", "berkeley", "UPenn",
                "yale", "columbia", "princeton", "ufl"],
    "Miscellaneous": ["gaming", "popculturechat", "AskHistorians", "conspiracytheories", "teenagers", 
                      "lgbt", "4chan", "philosophy"]
}

export const subreddits = [
    "AskReddit",
    "technology",
    "politics",
    "explainlikeimfive",
    "NoStupidQuestions",
    "gaming",
    "science",
    "popculturechat",
    "cscareerquestions",
    "stocks",
    "investing",
    "artificial",
    "AskHistorians",
    "unpopularopinion",
    "philosophy",
    "teenagers",
    "AskMen",
    "AskWomen",
    "personalfinance",
    "changemyview",
    "ApplyingToCollege",
    "conspiracytheories",
    "lgbt",
    "Bitcoin",
    "Futurology",
    "4chan",
    "uofm",
    "Harvard",
    "stanford", 
    "mit",
    "berkeley",
    "UPenn",
    "yale",
    "columbia",
    "princeton",
    "ufl",
];